# Final Project - Foundations of Data Science: Programming and Linear Algebra (CDSCO1001U)

## Question 2: Hammins's Code

In [1]:
import numpy as np

### Define relevant matrices

In [6]:
# Define Generator Matrix G
Matrix_G = np.array([[1,1,0,1], 
                    [1,0,1,1], 
                    [1,0,0,0], 
                    [0,1,1,1], 
                    [0,1,0,0], 
                    [0,0,1,0], 
                    [0,0,0,1]])

# Define Parity-Check Matrix H
Matrix_H = np.array([[1,0,1,0,1,0,1],
                    [0,1,1,0,0,1,1],
                    [0,0,0,1,1,1,1]])

# Define Decoder Matrix R
Matrix_R = np.array([[0,0,1,0,0,0,0],
                    [0,0,0,0,1,0,0],
                    [0,0,0,0,0,1,0],
                    [0,0,0,0,0,0,1]])

### 2.1 Hamming Encoder:

In [69]:
class Hamming_Encoder_7_4:
    def __init__(self):
        
        # Define Encoder Matrix G as defined in Task.
        self.G = np.array([[1,1,0,1], 
                    [1,0,1,1], 
                    [1,0,0,0], 
                    [0,1,1,1], 
                    [0,1,0,0], 
                    [0,0,1,0], 
                    [0,0,0,1]])
        
        # Define Parity Check Matrix H as described in Task.
        self.H = np.array([[1,0,1,0,1,0,1],
                    [0,1,1,0,0,1,1],
                    [0,0,0,1,1,1,1]])
    
    # Encoder function:    
    def encoder(self, value):
        # Value must be a 4-bit binary value. Check len to gurantee a list of four entries.
        if len(value) != 4 & type(value) != list:
            raise ValueError("Value must be of 4-bit list of binary values!")
        
        # Reshape binray vector to (4,1) for proper multiplication as encoder matrix G has the dimensions (7,4)
        encode_vector = np.array(value).reshape((4,1))
        
        # Create codeword by computing dot product of G and w as described in taks.
        # Apply %2 on the dorproduct for binary encoding (Source?)
        self.codeword_c = np.dot(self.G, encode_vector) % 2 # %2 for binary decoding! => Source
        
        #returns a codeword that is (7,1) vector
        return self.codeword_c
        
    # Parity Check funciton:
    def parity_check(self):
        # Check that codeword is indeed a 7-bit vector.
        if len(self.codeword_c) != 7:
            raise ValueError("Codeword must be of 7-bit binary value!")
        
        # Reshape codeword vector for proper multiplciation as parity check matrix H has dimenisons (3,7)
        codeword_vector = np.array(self.codeword_c).reshape((7,1))
        
        #Calculate parity check by computing dort product of H and codeword as described in task
        # Apply %2 on the dorproduct for binary encoding (Source?)
        parity_result = np.dot(self.H, codeword_vector) % 2
        
        # Check that result is actully a zero vector.
        return np.all(parity_result == 0)
            

### 2.2 Hamming Decoder

In [70]:
# What is the problem with R? How to inherit 
class Hamming_Decoder_7_4(Hamming_Encoder_7_4):
    
    def __init__(self):
        # Inherit Functions of Encoder Class!
        super().__init__()
        
        #Define Decoder Matrix R as described in description 
        self.R = np.array([[0,0,1,0,0,0,0],
                    [0,0,0,0,1,0,0],
                    [0,0,0,0,0,1,0],
                    [0,0,0,0,0,0,1]])
    
    # Define decoder function
    def decoder(self):
        #Check that calculated codeword in Hamming Ecoder is of length 7
        if len(self.codeword_c) != 7:
            raise ValueError("Codeword must be a 7-digit binary codeword")
            
        # Reshape codeword vector for proper multiplciation as decoder matrix R has dimenisons (4,7) 
        codeword_c_vector = np.array(self.codeword_c).reshape((7,1))
        
        #Decode codeword by computing dot prodcut of R and codeword vector
        # Reshape to get identical vector as input
        decoded_value = (np.dot(self.R, codeword_c_vector) % 2).reshape((1,4))
        
        return decoded_value

### 2.3

In [2]:
vector1 = [1,0,1,0]
vector2 = [1,1,1,1]
vector3 = [0,0,1,1]
vector4 = [1,1,0,0]

In [71]:
test1 = Hamming_Encoder_7_4()

In [72]:
test1.encoder(vector1)

array([[1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0]])

In [73]:
test1.parity_check()

True

In [74]:
Decoding1 = Hamming_Decoder_7_4

In [75]:
Decoding1.decoder(test1)

AttributeError: 'Hamming_Encoder_7_4' object has no attribute 'R'

### Further Testing of Functions

In [3]:
testvector = [1,1,0,0]

In [4]:
reshapedvector = np.array(vector2).reshape((4,1))
reshapedvector

array([[1],
       [1],
       [1],
       [1]])

In [7]:
c = np.dot(Matrix_G, reshapedvector) % 2
c

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [8]:
check = np.dot(Matrix_H, c) % 2
check

array([[0],
       [0],
       [0]])

In [56]:
np.all(check == 0)

True

In [57]:
decode = np.dot(Matrix_R, c).reshape((1,4))
print(decode)

[[1 1 1 1]]
